services:
  db:
    image: postgis/postgis:15-3.4
    container_name: urbanmesh_db
    environment:
      POSTGRES_USER: urbanmesh_user
      POSTGRES_PASSWORD: urbanmesh_pass
      POSTGRES_DB: urbanmesh_db
    ports:
      - "5432:5432"
    volumes:
      - urbanmesh_data:/var/lib/postgresql/data

volumes:
  urbanmesh_data: